"""Path resolution and shared constants.

Every path in this project is derived from the repository root, which is located
by walking up from this file. Nothing is hardcoded to a machine, so the notebooks
run from any checkout location.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

DATA = ROOT / "data"
LCA_RAW = DATA / "lca"            # manual DOL download, not in the repo
LCA_SLIM = DATA / "lca_slim"      # regenerated by 01_extract_lca
OUTPUT = ROOT / "output"
FIGURES = OUTPUT / "figures"
TABLES = OUTPUT / "tables"

for _d in (DATA, LCA_SLIM, OUTPUT, FIGURES, TABLES):
    _d.mkdir(parents=True, exist_ok=True)

# Fiscal years. USCIS publishes FY2017-FY2023; DOL LCA coverage stops at FY2022,
# and FY2023 is a partial year, so models are fitted on FY2017-FY2022.
USCIS_YEARS = range(2017, 2024)
LCA_YEARS = range(2017, 2023)
MODEL_YEARS = range(2017, 2023)
